version: '2'
networks:
  byfn:
services:
  
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - byfn

  peer0.Universitiy.example.com:
    image: hyperledger/fabric-peer
    container_name: peer0.Universitiy.example.com
    environment:
      - CORE_PEER_ID=peer0.Universitiy.example.com
      - CORE_PEER_ADDRESS=peer0.Universitiy.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Universitiy.example.com:7051
      - CORE_PEER_LOCALMSPID=UniversitiyMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/Universitiy.example.com/peers/peer0.Universitiy.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/Universitiy.example.com/peers/peer0.Universitiy.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - byfn

  peer0.Compani.example.com:
    image: hyperledger/fabric-peer
    container_name: peer0.Compani.example.com
    environment:
      - CORE_PEER_ID=peer0.Compani.example.com
      - CORE_PEER_ADDRESS=peer0.Compani.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Compani.example.com:7051
      - CORE_PEER_LOCALMSPID=CompaniMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/Compani.example.com/peers/peer0.Compani.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/Compani.example.com/peers/peer0.Compani.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - byfn

  peer0.Student.example.com:
    image: hyperledger/fabric-peer
    container_name: peer0.Student.example.com
    environment:
      - CORE_PEER_ID=peer0.Student.example.com
      - CORE_PEER_ADDRESS=peer0.Student.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Student.example.com:7051
      - CORE_PEER_LOCALMSPID=StudentMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/Student.example.com/peers/peer0.Student.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/Student.example.com/peers/peer0.Student.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - byfn

  peer0.Verifier.example.com:
    image: hyperledger/fabric-peer
    container_name: peer0.Verifier.example.com
    environment:
      - CORE_PEER_ID=peer0.Verifier.example.com
      - CORE_PEER_ADDRESS=peer0.Verifier.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Verifier.example.com:7051
      - CORE_PEER_LOCALMSPID=VerifierMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/Verifier.example.com/peers/peer0.Verifier.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/Verifier.example.com/peers/peer0.Verifier.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.Universitiy.example.com:7051
      - CORE_PEER_LOCALMSPID=UniversitiyMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Universitiy.example.com/peers/peer0.Universitiy.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Universitiy.example.com/peers/peer0.Universitiy.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Universitiy.example.com/peers/peer0.Universitiy.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Universitiy.example.com/users/Admin@Universitiy.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 1000'
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /var/run:/host/var/run/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./../chaincode:/opt/gopath/src/github.com/chaincode
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - byfn